/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/version': {
    /** Daemon build version */
    get: operations['getVersion'];
  };
  '/v1/health': {
    /** Liveness probe */
    get: operations['getHealth'];
  };
  '/v1/identity': {
    /**
     * Board identity (board token + public key + UHWID)
     * @description Returns a freshly-minted short-lived ES256 board token, the
     * provisioning public key (PEM), and the board's UHWID. App Lab forwards
     * the board token to the Arduino backend to authenticate the board.
     */
    get: operations['getIdentity'];
  };
  '/v1/status': {
    /** Composed daemon + provisioning + cloud status */
    get: operations['getStatus'];
  };
  '/v1/provisioning/start': {
    /**
     * Trigger (re)provisioning
     * @description Asks the daemon FSM to (re)provision. The call BLOCKS until the
     * synchronous prelude — write the in-flight marker and wipe the old
     * credentials — has run, so the response reflects whether that committed
     * step succeeded; the longer CSR attempt (with retry) then proceeds
     * asynchronously. A request while the FSM is not parked waiting for a
     * command (an attempt already in flight, or a non-command state such as
     * CheckInternet) returns `409`. If the prelude itself fails (e.g. a disk
     * error), `500` is returned and the caller can safely retry.
     *
     * The request body is optional and may carry an `organization_id`; when
     * supplied it is persisted as part of the prelude. Omit it (or send an
     * empty body) to provision without an associated organization.
     */
    post: operations['startProvisioning'];
  };
  '/v1/variables/{name}': {
    /**
     * Set a variable value (outbound to cloud)
     * @description Stores the variable's value (with the current timestamp), notifies SSE
     * subscribers, and publishes it to the cloud property topic. The variable
     * is created on first use — there is no separate registration step.
     * The cloud publish is best-effort: if the daemon is not yet in
     * steady state the value is kept locally and pushed on the next
     * LastValues cycle.
     */
    put: operations['setVariableValue'];
  };
  '/v1/variables/{name}/events': {
    /**
     * Stream value updates (Server-Sent Events)
     * @description Opens a `text/event-stream` connection (the variable is created on
     * first use if it does not exist yet). The first event sent is named
     * `lastvalue` and replays the variable's current stored value and
     * timestamp (also flagged `last_value: true` in the payload) so a freshly
     * connected app can seed its local state; it is omitted only if the
     * variable has never been set. Every subsequent change is sent as an
     * `update` event. Multiple apps may subscribe to the same variable
     * concurrently — each receives its own last-value replay. Slow consumers
     * drop events rather than blocking the producer.
     */
    get: operations['streamVariableEvents'];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    VersionResponse: {
      /**
       * @description Daemon build version. Mock builds end with `-mock`.
       * @example 0.1.0
       */
      version: string;
    };
    IdentityResponse: {
      /**
       * @description Short-lived ES256 JWT. The `iss` claim carries the UHWID; the
       * server enforces a 10-minute window on `iat` (no `exp`).
       *
       * @example eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhMWIyYzMuLi4ifQ.SIG
       */
      board_token: string;
      /**
       * @description Provisioning public key in PEM format.
       * @example -----BEGIN PUBLIC KEY-----
       * MFkwEwYHKoZI...
       * -----END PUBLIC KEY-----
       */
      public_key_pem: string;
      /**
       * @description Unique hardware ID — 64-char lowercase hex SHA-256. Same value as the token's `iss` claim.
       * @example 3a7bd3e2360a3d29eea436fcfb7e44c735d117c42d1c1835420b6b9942dd4f1b
       */
      uhwid: string;
    };
    StatusResponse: {
      provisioning: components['schemas']['ProvisioningState'];
      daemon: components['schemas']['DaemonState'];
      /**
       * Format: uuid
       * @description Device UUID assigned by the cloud at provisioning time. Present only
       * when stored on disk (i.e. the board is provisioned); omitted otherwise.
       *
       * @example 7c9e6679-7425-40de-944b-e07fc1f90ae7
       */
      device_id?: string;
      /**
       * @description Organization the device was provisioned into. Optional — present only
       * when an `organization_id` was supplied to /v1/provisioning/start;
       * omitted otherwise (even for a provisioned board).
       *
       * @example a1b2c3d4-5566-7788-99aa-bbccddeeff00
       */
      organization_id?: string;
      /** @description Present only when `daemon` == `Run`; omitted otherwise. */
      cloud?: components['schemas']['CloudStatus'];
    };
    CloudStatus: {
      state: components['schemas']['CloudState'];
      /**
       * Format: uuid
       * @description Attached Thing UUID. Omitted when no Thing is attached yet.
       * @example 9f1c2d3e-4567-89ab-cdef-0123456789ab
       */
      thing_id?: string;
    };
    /**
     * @description Provisioning service state, derived from disk (no dedicated state file):
     * the in-flight marker takes precedence over the credential files.
     * `provisioning` = an attempt is in flight within its retry window;
     * `error` = an in-flight attempt exceeded the retry window and is awaiting a
     * new /v1/provisioning/start; `provisioned` = credentials present, no marker;
     * `unprovisioned` = no credentials and no attempt in flight.
     *
     * @enum {string}
     */
    ProvisioningState:
      | 'unprovisioned'
      | 'provisioning'
      | 'provisioned'
      | 'error';
    /**
     * @description Top-level daemon FSM macro state.
     * @enum {string}
     */
    DaemonState: 'CheckInternet' | 'Provisioning' | 'Run';
    /**
     * @description Nested Cloud FSM lifecycle state (only meaningful while daemon == Run).
     * @enum {string}
     */
    CloudState:
      | 'Disconnected'
      | 'Reconnecting'
      | 'Connecting'
      | 'AnnouncingDevice'
      | 'AwaitingThingID'
      | 'SyncingLastValues'
      | 'Steady';
    /** @description Optional body for POST /v1/provisioning/start. */
    StartProvisioningRequest: {
      /**
       * @description Organization the board should be provisioned into. Optional; when
       * absent or empty the board is provisioned without an associated
       * organization.
       *
       * @example a1b2c3d4-5566-7788-99aa-bbccddeeff00
       */
      organization_id?: string;
    };
    AcceptedResponse: {
      /**
       * @example accepted
       * @enum {string}
       */
      status: 'accepted';
    };
    Variable: {
      /** @example temperature */
      name: string;
      /**
       * @description Current value (any JSON value — number, bool, string, object,
       * array). Omitted when no value has been set yet.
       *
       * @example 21.5
       */
      value?: unknown;
      /**
       * Format: date-time
       * @description Moment the current value was last set, locally or by the cloud
       * (the "last value" timestamp). Omitted when no value has been set.
       *
       * @example 2026-06-22T10:00:00Z
       */
      timestamp?: string;
    };
    SendValueRequest: {
      /**
       * @description New value for the variable. Any JSON value (number, string,
       * boolean, object, array, null).
       *
       * @example 21.5
       */
      value: unknown;
    };
    /** @description One Server-Sent Event payload (the JSON after the SSE `data:` prefix). */
    UpdateEvent: {
      /** @example temperature */
      name: string;
      /**
       * @description New value. Any JSON value.
       * @example 22.7
       */
      value: unknown;
      /**
       * Format: date-time
       * @description Moment the value was set (cloud change time, or local PUT time).
       * @example 2026-06-22T10:00:00Z
       */
      timestamp: string;
      /**
       * @description True only on the first event of a stream (the `lastvalue` event,
       * replaying the current stored value). Omitted (false) on live
       * `update` events.
       *
       * @example true
       */
      last_value?: boolean;
    };
    /** @description Standard error envelope returned by failing endpoints. */
    Error: {
      /**
       * @description Human-readable error category.
       * @example variable not found
       */
      error: string;
      /**
       * @description Underlying error message.
       * @example variable "temperature" not found
       */
      details: string;
    };
  };
  responses: never;
  parameters: {
    /**
     * @description The registered variable name.
     * @example temperature
     */
    VariableName: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** Daemon build version */
  getVersion: {
    responses: {
      /** @description The daemon version string. Mock builds carry a `-mock` suffix. */
      200: {
        content: {
          'application/json': components['schemas']['VersionResponse'];
        };
      };
    };
  };
  /** Liveness probe */
  getHealth: {
    responses: {
      /** @description Daemon is alive. Empty body. */
      200: {
        content: never;
      };
    };
  };
  /**
   * Board identity (board token + public key + UHWID)
   * @description Returns a freshly-minted short-lived ES256 board token, the
   * provisioning public key (PEM), and the board's UHWID. App Lab forwards
   * the board token to the Arduino backend to authenticate the board.
   */
  getIdentity: {
    responses: {
      /** @description Identity payload. */
      200: {
        content: {
          'application/json': components['schemas']['IdentityResponse'];
        };
      };
      /**
       * @description Could not load the provisioning key, generate the board token, or
       * load the public key.
       */
      500: {
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  /** Composed daemon + provisioning + cloud status */
  getStatus: {
    responses: {
      /**
       * @description Composed snapshot. The `cloud` object is present only when the
       * daemon FSM is in the `Run` state.
       */
      200: {
        content: {
          'application/json': components['schemas']['StatusResponse'];
        };
      };
    };
  };
  /**
   * Trigger (re)provisioning
   * @description Asks the daemon FSM to (re)provision. The call BLOCKS until the
   * synchronous prelude — write the in-flight marker and wipe the old
   * credentials — has run, so the response reflects whether that committed
   * step succeeded; the longer CSR attempt (with retry) then proceeds
   * asynchronously. A request while the FSM is not parked waiting for a
   * command (an attempt already in flight, or a non-command state such as
   * CheckInternet) returns `409`. If the prelude itself fails (e.g. a disk
   * error), `500` is returned and the caller can safely retry.
   *
   * The request body is optional and may carry an `organization_id`; when
   * supplied it is persisted as part of the prelude. Omit it (or send an
   * empty body) to provision without an associated organization.
   */
  startProvisioning: {
    requestBody?: {
      content: {
        /**
         * @example {
         *   "organization_id": "a1b2c3d4-5566-7788-99aa-bbccddeeff00"
         * }
         */
        'application/json': components['schemas']['StartProvisioningRequest'];
      };
    };
    responses: {
      /**
       * @description Prelude committed (marker written, old credentials wiped); the CSR
       * attempt runs asynchronously.
       */
      202: {
        content: {
          'application/json': components['schemas']['AcceptedResponse'];
        };
      };
      /** @description A provisioning is already in progress, or the daemon is not ready to accept the request. */
      409: {
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
      /** @description The provisioning prelude failed (e.g. could not write the marker or wipe credentials); safe to retry. */
      500: {
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  /**
   * Set a variable value (outbound to cloud)
   * @description Stores the variable's value (with the current timestamp), notifies SSE
   * subscribers, and publishes it to the cloud property topic. The variable
   * is created on first use — there is no separate registration step.
   * The cloud publish is best-effort: if the daemon is not yet in
   * steady state the value is kept locally and pushed on the next
   * LastValues cycle.
   */
  setVariableValue: {
    parameters: {
      path: {
        name: components['parameters']['VariableName'];
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SendValueRequest'];
      };
    };
    responses: {
      /** @description Value set. Empty body. */
      204: {
        content: never;
      };
      /** @description Malformed JSON body. */
      400: {
        content: {
          'application/json': components['schemas']['Error'];
        };
      };
    };
  };
  /**
   * Stream value updates (Server-Sent Events)
   * @description Opens a `text/event-stream` connection (the variable is created on
   * first use if it does not exist yet). The first event sent is named
   * `lastvalue` and replays the variable's current stored value and
   * timestamp (also flagged `last_value: true` in the payload) so a freshly
   * connected app can seed its local state; it is omitted only if the
   * variable has never been set. Every subsequent change is sent as an
   * `update` event. Multiple apps may subscribe to the same variable
   * concurrently — each receives its own last-value replay. Slow consumers
   * drop events rather than blocking the producer.
   */
  streamVariableEvents: {
    parameters: {
      path: {
        name: components['parameters']['VariableName'];
      };
    };
    responses: {
      /**
       * @description SSE stream established. Body is an open `text/event-stream`; each
       * event has the form
       * `event: <lastvalue|update>\ndata: {"name":...,"value":...,"timestamp":...}\n\n`.
       */
      200: {
        headers: {
          'Cache-Control'?: string;
          Connection?: string;
        };
        content: {
          'text/event-stream': components['schemas']['UpdateEvent'];
        };
      };
    };
  };
}
