// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agent} from '../models';
import {app} from '../models';
import {carrier} from '../models';
import {flasher} from '../models';
import {assetserver} from '../models';
import {board} from '../models';
import {options} from '../models';
import {ethernet} from '../models';
import {fs} from '../models';
import {learn} from '../models';
import {wifi} from '../models';
import {httpclient} from '../models';
import {airuntime} from '../models';
import {lsp} from '../models';

export function AgentAuthMethods():Promise<Array<agent.AuthMethod>>;

export function AgentAuthStatus(arg1:string):Promise<agent.AuthStatus>;

export function AgentAuthenticate(arg1:string):Promise<void>;

export function AgentCancel(arg1:string):Promise<void>;

export function AgentCancelLogin(arg1:string):Promise<void>;

export function AgentChoicesReply(arg1:string,arg2:agent.ChoiceSubmission):Promise<void>;

export function AgentCloseSession(arg1:string):Promise<void>;

export function AgentDeleteSession(arg1:string):Promise<void>;

export function AgentDisconnect(arg1:string):Promise<void>;

export function AgentGetSessionState(arg1:string):Promise<agent.SessionState>;

export function AgentListSessions():Promise<Array<agent.SessionSummary>>;

export function AgentLoadSession(arg1:string):Promise<void>;

export function AgentNewSession(arg1:string):Promise<string>;

export function AgentPermissionReply(arg1:string,arg2:agent.PermissionOutcome):Promise<void>;

export function AgentPinSession(arg1:string,arg2:boolean):Promise<void>;

export function AgentPrompt(arg1:string,arg2:string):Promise<void>;

export function AgentRenameSession(arg1:string,arg2:string):Promise<void>;

export function AgentResolveFile(arg1:string):Promise<app.AgentFileLocation>;

export function AgentSetDefault(arg1:string):Promise<void>;

export function AgentSetSessionMode(arg1:string,arg2:string):Promise<void>;

export function AgentSetSessionModel(arg1:string,arg2:string):Promise<void>;

export function AgentSignIn(arg1:string):Promise<void>;

export function AgentSignInApiKey(arg1:string,arg2:string):Promise<void>;

export function AgentStart(arg1:string):Promise<void>;

export function AgentStop():Promise<void>;

export function AgentSubmitLoginToken(arg1:string,arg2:string):Promise<void>;

export function AgentValidateAuth():Promise<void>;

export function ApplyBoardUpdate(arg1:boolean,arg2:string):Promise<any>;

export function CancelFlash():Promise<void>;

export function CarrierDisable(arg1:string,arg2:string):Promise<carrier.ShowCarrierResult>;

export function CarrierEnable(arg1:string,arg2:string,arg3:Array<carrier.EnableDeviceConfig>):Promise<carrier.ShowCarrierResult>;

export function CarrierList():Promise<Array<carrier.Carrier>>;

export function CarrierShow(arg1:string):Promise<carrier.ShowResult>;

export function CheckAndApplyUpdate(arg1:boolean):Promise<void>;

export function CheckBoardUpdate(arg1:boolean,arg2:string):Promise<string>;

export function ConnectToWiFi(arg1:string,arg2:string):Promise<void>;

export function CreateFolder(arg1:string,arg2:boolean):Promise<void>;

export function DeleteRefreshToken(arg1:string):Promise<void>;

export function DisableNetworkMode(arg1:string):Promise<void>;

export function DisconnectWiFi():Promise<void>;

export function EnableNetworkMode(arg1:string):Promise<void>;

export function ExportApp(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function Flash(arg1:flasher.OSImageRelease,arg2:boolean):Promise<void>;

export function ForwardNonUIPort(arg1:number):Promise<void>;

export function GetAboutMessage():Promise<string>;

export function GetAssetMiddleware():Promise<assetserver.Middleware>;

export function GetAvailableFreeSpace():Promise<number>;

export function GetBoardList():Promise<Array<board.Board>>;

export function GetBoardName():Promise<string>;

export function GetBoardUpdateLogs(arg1:string):Promise<void>;

export function GetCloudConnectorURL():Promise<string>;

export function GetConnectionName():Promise<any>;

export function GetCurrentVersion():Promise<string>;

export function GetErrorFormatter():Promise<options.ErrorFormatter>;

export function GetEthStatus():Promise<ethernet.EthStatus>;

export function GetFeatureFlags():Promise<Array<string>>;

export function GetFileContent(arg1:string):Promise<string>;

export function GetFileTree(arg1:string):Promise<fs.FSNode>;

export function GetIPAddress():Promise<any>;

export function GetInternetStatus():Promise<boolean>;

export function GetKernelVersion():Promise<string>;

export function GetKeyboardLayout():Promise<string>;

export function GetLearnResource(arg1:learn.LearnResourceID):Promise<learn.FullLearnResource>;

export function GetLearnResourceList():Promise<Array<learn.LearnResourceEntry>>;

export function GetLinuxDistribution():Promise<string>;

export function GetLspTempWorkspaceAppDir():Promise<string>;

export function GetLspWorkspaceFile(arg1:string):Promise<string>;

export function GetNetworkModeStatus():Promise<boolean>;

export function GetOSImageVersion():Promise<string>;

export function GetOrchestratorURL():Promise<string>;

export function GetRefreshToken(arg1:string):Promise<string>;

export function GetTags():Promise<Array<learn.Tag>>;

export function GetTitle():Promise<string>;

export function GetWiFiStatus():Promise<wifi.WifiStatus>;

export function HandleSecondInstanceLaunch(arg1:options.SecondInstanceData):Promise<void>;

export function ImportAppFromPath(arg1:string):Promise<string>;

export function ImportFileToAppFromPath(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function ImportFolderToAppFromPath(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function InferOrchestratorURL():Promise<string>;

export function InitLspWorkspace(arg1:string):Promise<void>;

export function IsBoard():Promise<boolean>;

export function IsDirectory(arg1:string):Promise<boolean>;

export function IsLocalDirectory(arg1:string):Promise<boolean>;

export function IsLspEnabled():Promise<boolean>;

export function IsUserPartitionPreservationSupported(arg1:string,arg2:string):Promise<boolean>;

export function IsUserPasswordSet():Promise<boolean>;

export function ListAvailableOSImages():Promise<Array<flasher.OSImageRelease>>;

export function ListKeyboardLayouts():Promise<Array<board.KeyboardLayout>>;

export function ListSSIDs():Promise<Array<string>>;

export function MakeHTTPRequest(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>,arg5:string):Promise<httpclient.Response>;

export function NeedsImageUpdate():Promise<boolean>;

export function NewVersion():Promise<string>;

export function OnUrlOpen(arg1:string):Promise<void>;

export function OpenBoardTerminal():Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenUIWhenReady(arg1:number,arg2:number):Promise<void>;

export function RebootBoard(arg1:string):Promise<void>;

export function RemoveFile(arg1:string,arg2:boolean):Promise<void>;

export function RenameFile(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function RenameFolder(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function RuntimeCancelInstall(arg1:string):Promise<void>;

export function RuntimeCheckUpdate(arg1:string):Promise<airuntime.UpdateCheck>;

export function RuntimeInstall(arg1:string):Promise<void>;

export function RuntimeStatus(arg1:string):Promise<airuntime.Status>;

export function RuntimeUninstall(arg1:string):Promise<void>;

export function SelectAppDialog():Promise<string>;

export function SelectBoard(arg1:string,arg2:string):Promise<void>;

export function SelectFilesDialog(arg1:string):Promise<Array<string>>;

export function SelectFolderDialog(arg1:string):Promise<string>;

export function SendLSPMessage(arg1:lsp.LspId,arg2:any):Promise<void>;

export function SetBoardName(arg1:string):Promise<void>;

export function SetKeyboardLayout(arg1:string):Promise<void>;

export function SetRefreshToken(arg1:string,arg2:string):Promise<void>;

export function SetUserPassword(arg1:string):Promise<void>;

export function StartLSP(arg1:lsp.LspId,arg2:string):Promise<void>;

export function StopAllLSP():Promise<void>;

export function UnwatchAll():Promise<void>;

export function UnwatchApp(arg1:string):Promise<void>;

export function UnwatchAppsDir(arg1:string):Promise<void>;

export function WatchApp(arg1:string):Promise<void>;

export function WatchAppsDir(arg1:string):Promise<void>;

export function WriteFileContent(arg1:string,arg2:string,arg3:boolean):Promise<void>;
