// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AgentAuthMethods() {
  return window['go']['app']['App']['AgentAuthMethods']();
}

export function AgentAuthStatus(arg1) {
  return window['go']['app']['App']['AgentAuthStatus'](arg1);
}

export function AgentAuthenticate(arg1) {
  return window['go']['app']['App']['AgentAuthenticate'](arg1);
}

export function AgentCancel(arg1) {
  return window['go']['app']['App']['AgentCancel'](arg1);
}

export function AgentCancelLogin(arg1) {
  return window['go']['app']['App']['AgentCancelLogin'](arg1);
}

export function AgentChoicesReply(arg1, arg2) {
  return window['go']['app']['App']['AgentChoicesReply'](arg1, arg2);
}

export function AgentCloseSession(arg1) {
  return window['go']['app']['App']['AgentCloseSession'](arg1);
}

export function AgentDeleteSession(arg1) {
  return window['go']['app']['App']['AgentDeleteSession'](arg1);
}

export function AgentDisconnect(arg1) {
  return window['go']['app']['App']['AgentDisconnect'](arg1);
}

export function AgentGetSessionState(arg1) {
  return window['go']['app']['App']['AgentGetSessionState'](arg1);
}

export function AgentListSessions() {
  return window['go']['app']['App']['AgentListSessions']();
}

export function AgentLoadSession(arg1) {
  return window['go']['app']['App']['AgentLoadSession'](arg1);
}

export function AgentNewSession(arg1) {
  return window['go']['app']['App']['AgentNewSession'](arg1);
}

export function AgentPermissionReply(arg1, arg2) {
  return window['go']['app']['App']['AgentPermissionReply'](arg1, arg2);
}

export function AgentPinSession(arg1, arg2) {
  return window['go']['app']['App']['AgentPinSession'](arg1, arg2);
}

export function AgentPrompt(arg1, arg2) {
  return window['go']['app']['App']['AgentPrompt'](arg1, arg2);
}

export function AgentRenameSession(arg1, arg2) {
  return window['go']['app']['App']['AgentRenameSession'](arg1, arg2);
}

export function AgentResolveFile(arg1) {
  return window['go']['app']['App']['AgentResolveFile'](arg1);
}

export function AgentSetDefault(arg1) {
  return window['go']['app']['App']['AgentSetDefault'](arg1);
}

export function AgentSetSessionMode(arg1, arg2) {
  return window['go']['app']['App']['AgentSetSessionMode'](arg1, arg2);
}

export function AgentSetSessionModel(arg1, arg2) {
  return window['go']['app']['App']['AgentSetSessionModel'](arg1, arg2);
}

export function AgentSignIn(arg1) {
  return window['go']['app']['App']['AgentSignIn'](arg1);
}

export function AgentSignInApiKey(arg1, arg2) {
  return window['go']['app']['App']['AgentSignInApiKey'](arg1, arg2);
}

export function AgentStart(arg1) {
  return window['go']['app']['App']['AgentStart'](arg1);
}

export function AgentStop() {
  return window['go']['app']['App']['AgentStop']();
}

export function AgentSubmitLoginToken(arg1, arg2) {
  return window['go']['app']['App']['AgentSubmitLoginToken'](arg1, arg2);
}

export function AgentValidateAuth() {
  return window['go']['app']['App']['AgentValidateAuth']();
}

export function ApplyBoardUpdate(arg1, arg2) {
  return window['go']['app']['App']['ApplyBoardUpdate'](arg1, arg2);
}

export function CancelFlash() {
  return window['go']['app']['App']['CancelFlash']();
}

export function CarrierDisable(arg1, arg2) {
  return window['go']['app']['App']['CarrierDisable'](arg1, arg2);
}

export function CarrierEnable(arg1, arg2, arg3) {
  return window['go']['app']['App']['CarrierEnable'](arg1, arg2, arg3);
}

export function CarrierList() {
  return window['go']['app']['App']['CarrierList']();
}

export function CarrierShow(arg1) {
  return window['go']['app']['App']['CarrierShow'](arg1);
}

export function CheckAndApplyUpdate(arg1) {
  return window['go']['app']['App']['CheckAndApplyUpdate'](arg1);
}

export function CheckBoardUpdate(arg1, arg2) {
  return window['go']['app']['App']['CheckBoardUpdate'](arg1, arg2);
}

export function ConnectToWiFi(arg1, arg2) {
  return window['go']['app']['App']['ConnectToWiFi'](arg1, arg2);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['app']['App']['CreateFolder'](arg1, arg2);
}

export function DeleteRefreshToken(arg1) {
  return window['go']['app']['App']['DeleteRefreshToken'](arg1);
}

export function DisableNetworkMode(arg1) {
  return window['go']['app']['App']['DisableNetworkMode'](arg1);
}

export function DisconnectWiFi() {
  return window['go']['app']['App']['DisconnectWiFi']();
}

export function EnableNetworkMode(arg1) {
  return window['go']['app']['App']['EnableNetworkMode'](arg1);
}

export function ExportApp(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExportApp'](arg1, arg2, arg3);
}

export function Flash(arg1, arg2) {
  return window['go']['app']['App']['Flash'](arg1, arg2);
}

export function ForwardNonUIPort(arg1) {
  return window['go']['app']['App']['ForwardNonUIPort'](arg1);
}

export function GetAboutMessage() {
  return window['go']['app']['App']['GetAboutMessage']();
}

export function GetAssetMiddleware() {
  return window['go']['app']['App']['GetAssetMiddleware']();
}

export function GetAvailableFreeSpace() {
  return window['go']['app']['App']['GetAvailableFreeSpace']();
}

export function GetBoardList() {
  return window['go']['app']['App']['GetBoardList']();
}

export function GetBoardName() {
  return window['go']['app']['App']['GetBoardName']();
}

export function GetBoardUpdateLogs(arg1) {
  return window['go']['app']['App']['GetBoardUpdateLogs'](arg1);
}

export function GetCloudConnectorURL() {
  return window['go']['app']['App']['GetCloudConnectorURL']();
}

export function GetConnectionName() {
  return window['go']['app']['App']['GetConnectionName']();
}

export function GetCurrentVersion() {
  return window['go']['app']['App']['GetCurrentVersion']();
}

export function GetErrorFormatter() {
  return window['go']['app']['App']['GetErrorFormatter']();
}

export function GetEthStatus() {
  return window['go']['app']['App']['GetEthStatus']();
}

export function GetFeatureFlags() {
  return window['go']['app']['App']['GetFeatureFlags']();
}

export function GetFileContent(arg1) {
  return window['go']['app']['App']['GetFileContent'](arg1);
}

export function GetFileTree(arg1) {
  return window['go']['app']['App']['GetFileTree'](arg1);
}

export function GetIPAddress() {
  return window['go']['app']['App']['GetIPAddress']();
}

export function GetInternetStatus() {
  return window['go']['app']['App']['GetInternetStatus']();
}

export function GetKernelVersion() {
  return window['go']['app']['App']['GetKernelVersion']();
}

export function GetKeyboardLayout() {
  return window['go']['app']['App']['GetKeyboardLayout']();
}

export function GetLearnResource(arg1) {
  return window['go']['app']['App']['GetLearnResource'](arg1);
}

export function GetLearnResourceList() {
  return window['go']['app']['App']['GetLearnResourceList']();
}

export function GetLinuxDistribution() {
  return window['go']['app']['App']['GetLinuxDistribution']();
}

export function GetLspTempWorkspaceAppDir() {
  return window['go']['app']['App']['GetLspTempWorkspaceAppDir']();
}

export function GetLspWorkspaceFile(arg1) {
  return window['go']['app']['App']['GetLspWorkspaceFile'](arg1);
}

export function GetNetworkModeStatus() {
  return window['go']['app']['App']['GetNetworkModeStatus']();
}

export function GetOSImageVersion() {
  return window['go']['app']['App']['GetOSImageVersion']();
}

export function GetOrchestratorURL() {
  return window['go']['app']['App']['GetOrchestratorURL']();
}

export function GetRefreshToken(arg1) {
  return window['go']['app']['App']['GetRefreshToken'](arg1);
}

export function GetTags() {
  return window['go']['app']['App']['GetTags']();
}

export function GetTitle() {
  return window['go']['app']['App']['GetTitle']();
}

export function GetWiFiStatus() {
  return window['go']['app']['App']['GetWiFiStatus']();
}

export function HandleSecondInstanceLaunch(arg1) {
  return window['go']['app']['App']['HandleSecondInstanceLaunch'](arg1);
}

export function ImportAppFromPath(arg1) {
  return window['go']['app']['App']['ImportAppFromPath'](arg1);
}

export function ImportFileToAppFromPath(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ImportFileToAppFromPath'](arg1, arg2, arg3, arg4);
}

export function ImportFolderToAppFromPath(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ImportFolderToAppFromPath'](arg1, arg2, arg3, arg4);
}

export function InferOrchestratorURL() {
  return window['go']['app']['App']['InferOrchestratorURL']();
}

export function InitLspWorkspace(arg1) {
  return window['go']['app']['App']['InitLspWorkspace'](arg1);
}

export function IsBoard() {
  return window['go']['app']['App']['IsBoard']();
}

export function IsDirectory(arg1) {
  return window['go']['app']['App']['IsDirectory'](arg1);
}

export function IsLocalDirectory(arg1) {
  return window['go']['app']['App']['IsLocalDirectory'](arg1);
}

export function IsLspEnabled() {
  return window['go']['app']['App']['IsLspEnabled']();
}

export function IsUserPartitionPreservationSupported(arg1, arg2) {
  return window['go']['app']['App']['IsUserPartitionPreservationSupported'](arg1, arg2);
}

export function IsUserPasswordSet() {
  return window['go']['app']['App']['IsUserPasswordSet']();
}

export function ListAvailableOSImages() {
  return window['go']['app']['App']['ListAvailableOSImages']();
}

export function ListKeyboardLayouts() {
  return window['go']['app']['App']['ListKeyboardLayouts']();
}

export function ListSSIDs() {
  return window['go']['app']['App']['ListSSIDs']();
}

export function MakeHTTPRequest(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['MakeHTTPRequest'](arg1, arg2, arg3, arg4, arg5);
}

export function NeedsImageUpdate() {
  return window['go']['app']['App']['NeedsImageUpdate']();
}

export function NewVersion() {
  return window['go']['app']['App']['NewVersion']();
}

export function OnUrlOpen(arg1) {
  return window['go']['app']['App']['OnUrlOpen'](arg1);
}

export function OpenBoardTerminal() {
  return window['go']['app']['App']['OpenBoardTerminal']();
}

export function OpenFile(arg1) {
  return window['go']['app']['App']['OpenFile'](arg1);
}

export function OpenUIWhenReady(arg1, arg2) {
  return window['go']['app']['App']['OpenUIWhenReady'](arg1, arg2);
}

export function RebootBoard(arg1) {
  return window['go']['app']['App']['RebootBoard'](arg1);
}

export function RemoveFile(arg1, arg2) {
  return window['go']['app']['App']['RemoveFile'](arg1, arg2);
}

export function RenameFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['RenameFile'](arg1, arg2, arg3);
}

export function RenameFolder(arg1, arg2, arg3) {
  return window['go']['app']['App']['RenameFolder'](arg1, arg2, arg3);
}

export function RuntimeCancelInstall(arg1) {
  return window['go']['app']['App']['RuntimeCancelInstall'](arg1);
}

export function RuntimeCheckUpdate(arg1) {
  return window['go']['app']['App']['RuntimeCheckUpdate'](arg1);
}

export function RuntimeInstall(arg1) {
  return window['go']['app']['App']['RuntimeInstall'](arg1);
}

export function RuntimeStatus(arg1) {
  return window['go']['app']['App']['RuntimeStatus'](arg1);
}

export function RuntimeUninstall(arg1) {
  return window['go']['app']['App']['RuntimeUninstall'](arg1);
}

export function SelectAppDialog() {
  return window['go']['app']['App']['SelectAppDialog']();
}

export function SelectBoard(arg1, arg2) {
  return window['go']['app']['App']['SelectBoard'](arg1, arg2);
}

export function SelectFilesDialog(arg1) {
  return window['go']['app']['App']['SelectFilesDialog'](arg1);
}

export function SelectFolderDialog(arg1) {
  return window['go']['app']['App']['SelectFolderDialog'](arg1);
}

export function SendLSPMessage(arg1, arg2) {
  return window['go']['app']['App']['SendLSPMessage'](arg1, arg2);
}

export function SetBoardName(arg1) {
  return window['go']['app']['App']['SetBoardName'](arg1);
}

export function SetKeyboardLayout(arg1) {
  return window['go']['app']['App']['SetKeyboardLayout'](arg1);
}

export function SetRefreshToken(arg1, arg2) {
  return window['go']['app']['App']['SetRefreshToken'](arg1, arg2);
}

export function SetUserPassword(arg1) {
  return window['go']['app']['App']['SetUserPassword'](arg1);
}

export function StartLSP(arg1, arg2) {
  return window['go']['app']['App']['StartLSP'](arg1, arg2);
}

export function StopAllLSP() {
  return window['go']['app']['App']['StopAllLSP']();
}

export function UnwatchAll() {
  return window['go']['app']['App']['UnwatchAll']();
}

export function UnwatchApp(arg1) {
  return window['go']['app']['App']['UnwatchApp'](arg1);
}

export function UnwatchAppsDir(arg1) {
  return window['go']['app']['App']['UnwatchAppsDir'](arg1);
}

export function WatchApp(arg1) {
  return window['go']['app']['App']['WatchApp'](arg1);
}

export function WatchAppsDir(arg1) {
  return window['go']['app']['App']['WatchAppsDir'](arg1);
}

export function WriteFileContent(arg1, arg2, arg3) {
  return window['go']['app']['App']['WriteFileContent'](arg1, arg2, arg3);
}
