enableStrictSsl: false

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.5.0.cjs

npmScopes:
  bcmi-labs:
    npmRegistryServer: "https://npm.pkg.github.com"

plugins:
  - ./dev-utils/dev-config/scripts/plugin-env-npm.js