#!/bin/bash

# Turns the committed `licensed` caches into the notice files App Lab ships.
#
#   .licenses/app-lab-desktop/go       -> internal/notices/go-dependencies.txt
#   .licenses/cloud-editor-mono/npm    -> internal/notices/npm-dependencies.txt
#   vendored assets (no manifest)      -> internal/notices/vendored-assets.txt
#
# Both caches are the ones `licensed cache` (root .licensed.yml) maintains and
# `task general:cache-dep-licenses` regenerates — deliberately: the check-cache
# CI job regenerates that task and diffs, so a notice generated from any other
# cache would sit outside the freshness gate. (An earlier version read a
# separate cache under dev-utils/al-license that only the release job
# refreshed; its staleness was invisible to CI.)
#
# Why generate rather than use `licensed notices` directly: that command
# re-enumerates dependencies from the live tree instead of reading the cache, so
# its output depends on the machine it runs on. Run on macOS it silently dropped
# three Linux-only Go modules the CI cache contains. Reading the committed cache
# is deterministic, works offline, and is the same set CI already keeps honest.
#
# Both cache-driven files are deduplicated by licence text. Most cache entries
# are sub-packages of a shared module or packages under the same stock licence,
# and repeating the Apache-2.0 text a hundred times makes the notice harder to
# read without making it more complete. It also matters for size: these are
# embedded into the Windows binary, which is the only platform that gets no
# file copy.
#
# Freshness is enforced by the existing machinery: this runs as a step of
# `general:cache-dep-licenses`, and the check-cache job in
# check-npm-dependencies-task.yml regenerates that task and fails on any git
# diff. A stale notice surfaces exactly like a stale cache.

set -o pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
REPO_ROOT="$( cd "${SCRIPT_DIR}/../.." &> /dev/null && pwd )"
OUT_DIR="${REPO_ROOT}/standalone-apps/app-lab-desktop/internal/notices"

RED='\033[0;31m'; GREEN='\033[0;32m'; NC='\033[0m'
info() { echo -e "${GREEN}[INFO] $1${NC}"; }
error() { echo -e "${RED}[ERROR] $1${NC}"; }

command -v jq > /dev/null 2>&1 || { error "jq is required"; exit 1; }

# yq comes from the repo's own tool directives, so it needs no separate install.
yq() { ( cd "$REPO_ROOT" && go tool github.com/mikefarah/yq/v4 "$@" ); }

# generate <cache dir> <output file> <heading> <what these are>
generate() {
    local cache_dir="$1" out_file="$2" heading="$3" blurb="$4"

    if [ ! -d "$cache_dir" ]; then
        error "No licence cache at ${cache_dir}"
        return 1
    fi

    local dep_files=()
    while IFS= read -r f; do dep_files+=("$f"); done < <(find "$cache_dir" -name "*.dep.yml" | sort)

    if [ ${#dep_files[@]} -eq 0 ]; then
        error "No .dep.yml files under ${cache_dir}"
        return 1
    fi

    info "Reading ${#dep_files[@]} records from ${cache_dir#"$REPO_ROOT"/}..."

    # One yq call for all of them: through `go tool` its start-up cost makes a
    # per-file loop take minutes. -I=0 keeps one record per line for jq to slurp.
    local records
    records="$(yq -o=json -I=0 \
        '{"name": .name, "version": (.version // ""), "license": (.license // "unknown"), "texts": [.licenses[]?.text // ""]}' \
        "${dep_files[@]}")" || { error "yq failed on ${cache_dir}"; return 1; }

    local body
    body="$(printf '%s' "$records" | jq -s -r '
        group_by(.texts)
        | map({
            license:  (map(.license) | unique | join(", ")),
            packages: (map(.name + (if .version == "" then "" else " " + .version end)) | unique | sort),
            texts:    .[0].texts
          })
        | sort_by(.license, .packages[0])
        | .[]
        | "------------------------------------------------------------------------------\n"
          + "Licence: " + .license + "\n"
          + "Covers:\n"
          + (.packages | map("  " + .) | join("\n"))
          + "\n\n"
          + (.texts | map(select(. != "")) | join("\n\n"))
          + "\n"
    ')" || { error "grouping failed for ${cache_dir}"; return 1; }

    local groups
    groups="$(printf '%s\n' "$body" | grep -c '^Licence: ')"

    mkdir -p "$(dirname "$out_file")"
    {
        echo "$heading"
        printf '%.0s=' $(seq 1 ${#heading}); echo
        echo
        echo "$blurb"
        echo
        echo "Each distinct licence appears once, preceded by every package it covers."
        echo "Generated by dev-utils/al-license/generate_dependency_notices.sh from the"
        echo "licence metadata under .licenses. Do not edit by hand."
        echo
        echo "Packages: ${#dep_files[@]}"
        echo "Distinct licences: ${groups}"
        echo
        printf '%s\n' "$body"
    } > "$out_file"

    info "  -> ${out_file#"$REPO_ROOT"/}  (${#dep_files[@]} packages, ${groups} licences, $(wc -c < "$out_file" | tr -d ' ') bytes)"
}

# append_asset <out file> <name> <version> <url> <licence file>...
append_asset() {
    local out_file="$1" name="$2" version="$3" url="$4"
    shift 4

    local f
    for f in "$@"; do
        if [ ! -s "$f" ]; then
            error "Missing licence text for ${name}: ${f}"
            return 1
        fi
    done

    {
        echo
        echo "--------------------------------------------------------------------------------"
        echo "* ${name} (${version}) — ${url}"
        for f in "$@"; do
            echo
            cat "$f"
            echo
        done
    } >> "$out_file"
}

# Vendored assets have no package manifest, so `licensed` cannot see them and
# they appear in no cache. They still ship inside the frontend, so they still
# need attributing. Each asset keeps a verbatim copy of its upstream licence
# committed in the repo (kept honest by the script that vendors it); this
# collects them into one notice file.
generate_vendored() {
    local out_file="${OUT_DIR}/vendored-assets.txt"
    local heading="Arduino App Lab - notices for vendored assets"

    mkdir -p "$OUT_DIR"
    {
        echo "$heading"
        printf '%.0s=' $(seq 1 ${#heading}); echo
        echo
        echo "Assets vendored directly into the App Lab frontend rather than installed"
        echo "as packages. They have no manifest, so no dependency scanner sees them."
        echo
        echo "Generated by dev-utils/al-license/generate_dependency_notices.sh."
        echo "Do not edit by hand."
    } > "$out_file"

    # seti-ui file icons, pinned by SHA in the asset directory itself.
    local seti_dir="${REPO_ROOT}/ui-packages/images/assets/file-icons/seti"
    append_asset "$out_file" \
        "seti-ui" "$(cat "${seti_dir}/VERSION" 2>/dev/null || echo unknown)" \
        "https://github.com/jesseweed/seti-ui" \
        "${seti_dir}/LICENSE" || return 1

    # noto-emoji SVGs (emoji and waved region flags), fetched at build time by
    # internal/emoji/download_emojis.sh and embedded into the app. The tag is
    # read from that script so the notice cannot drift from what is downloaded,
    # and the script fails the download if the committed licence texts stop
    # matching the clone. The two parts are licensed differently: the emoji art
    # under the OFL 1.1 recorded in the repo's LICENSE, the region flags under
    # the public-domain statement in third_party/region-flags.
    local emoji_dir="${REPO_ROOT}/standalone-apps/app-lab-desktop/internal/emoji"
    local noto_tag
    noto_tag="$(sed -n 's/^REPO_TAG="\(.*\)"$/\1/p' "${emoji_dir}/download_emojis.sh")"
    if [ -z "$noto_tag" ]; then
        error "Could not read REPO_TAG from download_emojis.sh"
        return 1
    fi
    append_asset "$out_file" \
        "noto-emoji" "$noto_tag" \
        "https://github.com/googlefonts/noto-emoji" \
        "${emoji_dir}/noto-emoji.LICENSE.txt" || return 1
    append_asset "$out_file" \
        "noto-emoji region flags" "$noto_tag" \
        "https://github.com/googlefonts/noto-emoji/tree/${noto_tag}/third_party/region-flags" \
        "${emoji_dir}/region-flags.LICENSE.txt" || return 1

    # The socket.io browser bundle, fetched from jsDelivr at build time by
    # dev-utils/dev-config/scripts/download_socket_io.sh and embedded into
    # user-generated WebUI projects. Distinct from the socket.io-client in
    # npm-dependencies.txt, which is a different version installed through the
    # yarn tree. Version read from the script; the script verifies the
    # committed licence against upstream on every download.
    local socketio_dir="${REPO_ROOT}/dev-utils/dev-config/scripts"
    local socketio_version
    socketio_version="$(sed -n 's/^SOCKET_IO_VERSION="\(.*\)"$/\1/p' "${socketio_dir}/download_socket_io.sh")"
    if [ -z "$socketio_version" ]; then
        error "Could not read SOCKET_IO_VERSION from download_socket_io.sh"
        return 1
    fi
    append_asset "$out_file" \
        "socket.io-client (browser bundle)" "$socketio_version" \
        "https://github.com/socketio/socket.io-client" \
        "${socketio_dir}/socket.io-client.LICENSE.txt" || return 1

    info "  -> ${out_file#"$REPO_ROOT"/}  ($(wc -c < "$out_file" | tr -d ' ') bytes)"
}

# The repo-facing NOTICE, at the path it has always had so existing readers
# and mirrors keep finding it. Same content as the three shipped notices,
# concatenated — regenerated here from the same caches, so the check-cache job
# gates its freshness exactly like theirs. Its previous incarnation was
# written by `licensed notices`, which enumerates the live tree and therefore
# produced machine-dependent output; this one is deterministic, and being
# tracked, any stray `licensed notices` run that overwrites it shows up as a
# git diff instead of drifting silently.
generate_notice_file() {
    local out_file="${SCRIPT_DIR}/.licenses/NOTICE"

    {
        echo "Arduino App Lab - third-party notices"
        echo "====================================="
        echo
        echo "Attribution for the third-party code built into Arduino App Lab: the Go"
        echo "modules and npm packages compiled into the application, and the assets"
        echo "vendored without a package manifest. The licences of the executables App"
        echo "Lab bundles and runs as subprocesses (arduino-cli, clangd, node, the"
        echo "language servers) are kept separately in"
        echo "standalone-apps/app-lab-desktop/internal/notices/licenses/; see"
        echo "standalone-apps/app-lab-desktop/THIRD-PARTY-NOTICES.md for the full map"
        echo "of what ships where."
        echo
        echo "Generated by dev-utils/al-license/generate_dependency_notices.sh."
        echo "Do not edit by hand."
    } > "$out_file"

    local part
    for part in go-dependencies.txt npm-dependencies.txt vendored-assets.txt; do
        {
            echo
            echo
            printf '%.0s#' {1..78}; echo
            echo
            cat "${OUT_DIR}/${part}"
        } >> "$out_file"
    done

    info "  -> ${out_file#"$REPO_ROOT"/}  ($(wc -c < "$out_file" | tr -d ' ') bytes)"
}

generate "${REPO_ROOT}/.licenses/app-lab-desktop/go" \
         "${OUT_DIR}/go-dependencies.txt" \
         "Arduino App Lab - notices for linked Go modules" \
         "App Lab statically links the Go modules listed below into its executable." || exit 1

generate "${REPO_ROOT}/.licenses/cloud-editor-mono/npm" \
         "${OUT_DIR}/npm-dependencies.txt" \
         "Arduino App Lab - notices for bundled npm packages" \
         "App Lab is built from the npm packages listed below; those reached by its frontend are bundled into the application." || exit 1

generate_vendored || exit 1

generate_notice_file || exit 1

info "Done."
