/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/conversation': {
    /** Get conversation details */
    get: operations['getConversation'];
    /** Create user's conversation */
    post: operations['createConversation'];
    /** Update user's conversation */
    patch: operations['updateConversation'];
  };
  '/v1/conversation/messages': {
    /** Send a new message */
    post: operations['sendMessage'];
  };
  [path: `/v1/conversation/messages/${string}`]: {
    /** Retry processing a message */
    post: operations['retryMessage'];
    /** Delete a message */
    delete: operations['deleteMessage'];
  };
  '/v1/conversation/sketches': {
    /** Generate a new sketch based on a sketch plan */
    post: operations['newSketch'];
  };
  [
    path: `/v2/${'sketches' | 'examples' | 'libraries'}/${string}/conversation`
  ]: {
    /** Get conversation details for the given source and ID */
    get: operations['getConversationGeneric'];
    /** Create a new conversation for the given source and ID */
    post: operations['createConversationGeneric'];
    /** Update a conversation for the given source and ID */
    patch: operations['updateConversationGeneric'];
  };
  [
    path: `/v2/${
      | 'sketches'
      | 'examples'
      | 'libraries'}/${string}/conversation/messages`
  ]: {
    /** Send a new message and receive assistant responses via streaming for the given source */
    post: operations['sendMessageStreamGeneric'];
  };
  [
    path: `/v2/${
      | 'sketches'
      | 'examples'
      | 'libraries'}/${string}/conversation/follow-ups/error-fixes`
  ]: {
    /** Generate error fixes based on a previous error explanation message */
    post: operations['generateErrorFixesGeneric'];
  };
  [
    path: `/v2/${
      | 'sketches'
      | 'examples'
      | 'libraries'}/${string}/conversation/messages/${string}`
  ]: {
    /** Retry processing a message for the given source */
    post: operations['retryMessageGeneric'];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    NewConversationResponse: {
      /**
       * Format: uuid
       * @example 09290ae0-6291-4922-b3ac-d687960ae4fe
       */
      id: string;
      /**
       * Format: uuid
       * @example 72977b68-3d6e-45b0-a5fb-4b2eba06e6ed
       */
      userId: string;
      /**
       * @example sketch
       * @enum {string}
       */
      sourceType: 'sketch' | 'example' | 'library';
      /**
       * Format: uuid
       * @description Present if sourceType is "sketch"
       * @example 09290ae0-6291-4922-b3ac-d687960ae4fe
       */
      sketchId?: string | null;
      /**
       * @description Present if sourceType is "example"
       * @example Example
       */
      exampleId?: string | null;
      /**
       * @description Present if sourceType is "library"
       * @example Library
       */
      libraryId?: string | null;
      /**
       * Format: date-time
       * @example 2024-08-23T16:54:16.358416+02:00
       */
      creationTime: string;
      /** Format: date-time */
      lastInteraction: string;
      /** @example [] */
      history: components['schemas']['Message'][];
    };
    UpdateConversationRequest: {
      history: components['schemas']['Message'][];
    };
    /**
     * @example {
     *   "id": "09290ae0-6291-4922-b3ac-d687960ae4fe",
     *   "userId": "72977b68-3d6e-45b0-a5fb-4b2eba06e6ed",
     *   "sourceType": "example",
     *   "sketchId": "09290ae0-6291-4922-b3ac-d687960ae4fe",
     *   "creationTime": "2024-08-23T16:54:16.358416+02:00",
     *   "lastInteraction": "2024-08-23T16:54:16.358416+02:00",
     *   "history": []
     * }
     */
    ConversationResponse: {
      /**
       * Format: uuid
       * @example 09290ae0-6291-4922-b3ac-d687960ae4fe
       */
      id: string;
      /**
       * Format: uuid
       * @example 72977b68-3d6e-45b0-a5fb-4b2eba06e6ed
       */
      userId: string;
      /**
       * @example example
       * @enum {string}
       */
      sourceType: 'sketch' | 'example' | 'library';
      /**
       * Format: uuid
       * @description Present if sourceType is "sketch"
       * @example 09290ae0-6291-4922-b3ac-d687960ae4fe
       */
      sketchId?: string | null;
      /**
       * @description Present if sourceType is "example"
       * @example Example
       */
      exampleId?: string | null;
      /**
       * @description Present if sourceType is "library"
       * @example Library
       */
      libraryId?: string | null;
      /**
       * Format: date-time
       * @example 2024-08-23T16:54:16.358416+02:00
       */
      creationTime: string;
      /**
       * Format: date-time
       * @example 2024-08-23T16:54:16.358416+02:00
       */
      lastInteraction: string;
      history: components['schemas']['Message'][];
    };
    Message: {
      /** @example 1727953975116 */
      id: string;
      /**
       * Format: date-time
       * @example 2024-08-23T16:54:16.358416+02:00
       */
      timestamp: string;
      /** @enum {string} */
      type: 'assistant' | 'human';
      content:
        | components['schemas']['AssistantContent']
        | components['schemas']['HumanContent'];
      /**
       * @example sketch-plan/request
       * @enum {string}
       */
      tag?:
        | 'sketch-plan/request'
        | 'sketch-plan/response'
        | 'sketch-plan/generated-sketch'
        | 'error-explanation/request'
        | 'error-explanation/response'
        | 'error-explanation/error-fix'
        | 'error-fix/request'
        | 'error-fix/response';
      retrievedDocuments?: {
        title?: string;
        url?: string;
      }[];
    };
    AssistantContent: {
      /** @enum {string} */
      type: 'text' | 'code' | 'sketch-plan' | 'diff' | 'generated-sketch';
      data:
        | string
        | components['schemas']['SketchPlan']
        | components['schemas']['GeneratedSketch'];
    }[];
    SketchPlan: {
      components: string[];
      libraries: string[];
      codeInstructions: string[];
    };
    GeneratedSketch: {
      /** @example This is a sketch to blink the built-in LED. */
      introduction: string;
      code: string;
      /** @example Blink.ino */
      name: string;
    };
    HumanContent: {
      /** @example I'm a human */
      text: string;
      meta?: {
        /** @example Arduino Uno */
        board?: string;
      };
    };
    /**
     * @example event: message
     * data: [{"type":"text","data":"Hello"}]
     *
     * event: message
     * data: [{"type":"text","data":" world!"}]
     *
     * event: message
     * data: [{"type":"text","data":" world!"},{"type":"code","data":"void setup()"}]
     *
     * event: assistantMessageEnd
     * data: {"message":{"id":"1727953975116","timestamp":"2024-08-23T16:54:16.358416+02:00","type":"assistant"},"initiatingMessageId":"1727953975115","tag":"sketch-plan/request","retrievedDocuments":[{"title":"Blink","url":"https://www.arduino.cc/en/Tutorial/Blink"}]}
     */
    StreamedMessage: string;
    NewMessageRequest: {
      /** @enum {string} */
      type: 'human';
      content: {
        /** @example What is the best way to read a temperature sensor and send the data to Arduino Cloud? */
        text: string;
        meta?: {
          /** @example Arduino Uno */
          board?: string;
          errorFiles?: string[];
        };
      };
      /** @example sketch-plan/request */
      tag?: string;
    };
    NewMessageResponse: {
      message: components['schemas']['Message'];
      /** @example 1727953975115 */
      initiatingMessageId?: string;
    };
    NewSketchRequest: {
      /** @example 1727953975116 */
      sketchPlanId: string;
    };
    ErrorResponse: {
      /** @example bad request */
      err: string;
    };
  };
  responses: {
    /** @description Bad Request */
    BadRequest: {
      content: {
        'application/json': {
          /** @example Bad request */
          err: string;
        };
      };
    };
    /** @description Internal Server Error */
    InternalServerError: {
      content: {
        'application/json': {
          /** @example Internal server error */
          err: string;
        };
      };
    };
    /** @description Not Found */
    NotFound: {
      content: {
        'application/json': {
          /** @example Not found */
          err: string;
        };
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** Get conversation details */
  getConversation: {
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['ConversationResponse'];
        };
      };
      404: components['responses']['NotFound'];
      500: components['responses']['InternalServerError'];
    };
  };
  /** Create user's conversation */
  createConversation: {
    responses: {
      /** @description Created */
      201: {
        content: {
          'application/json': components['schemas']['NewConversationResponse'];
        };
      };
      /** @description See Other */
      303: {
        headers: {
          /** @description URL of the existing conversation */
          Location?: string;
        };
        content: never;
      };
      500: components['responses']['InternalServerError'];
    };
  };
  /** Update user's conversation */
  updateConversation: {
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateConversationRequest'];
      };
    };
    responses: {
      /** @description Updated */
      200: {
        content: {
          'application/json': components['schemas']['ConversationResponse'];
        };
      };
      /** @description Created */
      201: {
        content: {
          'application/json': components['schemas']['ConversationResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      500: components['responses']['InternalServerError'];
    };
  };
  /** Send a new message */
  sendMessage: {
    requestBody: {
      content: {
        'application/json': components['schemas']['NewMessageRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['NewMessageResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalServerError'];
    };
  };
  /** Retry processing a message */
  retryMessage: {
    parameters: {
      path: {
        messageId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['NewMessageResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalServerError'];
    };
  };
  /** Delete a message */
  deleteMessage: {
    parameters: {
      path: {
        messageId: string;
      };
    };
    responses: {
      /** @description No Content */
      204: {
        content: never;
      };
      400: components['responses']['BadRequest'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalServerError'];
    };
  };
  /** Generate a new sketch based on a sketch plan */
  newSketch: {
    requestBody: {
      content: {
        'application/json': components['schemas']['NewSketchRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['NewMessageResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalServerError'];
    };
  };
  /** Get conversation details for the given source and ID */
  getConversationGeneric: {
    parameters: {
      path: {
        source: 'sketches' | 'examples' | 'libraries';
        sourceId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['ConversationResponse'];
        };
      };
      404: components['responses']['NotFound'];
      500: components['responses']['InternalServerError'];
    };
  };
  /** Create a new conversation for the given source and ID */
  createConversationGeneric: {
    parameters: {
      path: {
        source: 'sketches' | 'examples' | 'libraries';
        /** @description The source identifier. For sketches it's a UUID, for others a string. */
        sourceId: string;
      };
    };
    responses: {
      /** @description Created */
      201: {
        content: {
          'application/json': components['schemas']['ConversationResponse'];
        };
      };
      /** @description See Other */
      303: {
        headers: {
          /** @description URL of the existing conversation */
          Location?: string;
        };
        content: never;
      };
      500: components['responses']['InternalServerError'];
    };
  };
  /** Update a conversation for the given source and ID */
  updateConversationGeneric: {
    parameters: {
      path: {
        source: 'sketches' | 'examples' | 'libraries';
        sourceId: string;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateConversationRequest'];
      };
    };
    responses: {
      /** @description Updated */
      200: {
        content: {
          'application/json': components['schemas']['ConversationResponse'];
        };
      };
      /** @description Created */
      201: {
        content: {
          'application/json': components['schemas']['ConversationResponse'];
        };
      };
      400: components['responses']['BadRequest'];
      500: components['responses']['InternalServerError'];
    };
  };
  /** Send a new message and receive assistant responses via streaming for the given source */
  sendMessageStreamGeneric: {
    parameters: {
      query?: {
        history?: 'true' | 'false' | '1' | '0';
      };
      path: {
        source: 'sketches' | 'examples' | 'libraries';
        sourceId: string;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['NewMessageRequest'];
      };
    };
    responses: {
      /** @description Streaming response of assistant messages in SSE format */
      200: {
        content: {
          'text/event-stream': components['schemas']['StreamedMessage'];
        };
      };
      400: components['responses']['BadRequest'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalServerError'];
    };
  };
  /** Generate error fixes based on a previous error explanation message */
  generateErrorFixesGeneric: {
    parameters: {
      path: {
        source: 'sketches' | 'examples' | 'libraries';
        sourceId: string;
      };
    };
    requestBody: {
      content: {
        'application/json': {
          /** @example 1727953975116 */
          errorExplanationId: string;
        };
      };
    };
    responses: {
      /** @description Streaming response of assistant messages in SSE */
      200: {
        content: {
          'text/event-stream': components['schemas']['StreamedMessage'];
        };
      };
      400: components['responses']['BadRequest'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalServerError'];
    };
  };
  /** Retry processing a message for the given source */
  retryMessageGeneric: {
    parameters: {
      path: {
        source: 'sketches' | 'examples' | 'libraries';
        sourceId: string;
        messageId: string;
      };
    };
    responses: {
      /** @description Streaming response of assistant messages in SSE */
      200: {
        content: {
          'text/event-stream': components['schemas']['StreamedMessage'];
        };
      };
      400: components['responses']['BadRequest'];
      404: components['responses']['NotFound'];
      500: components['responses']['InternalServerError'];
    };
  };
}
