/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/ota': {
    /**
     * List OTA
     * @description List OTA for a device
     */
    get: {
      parameters: {
        query: {
          /** @description Device ID */
          device_id: string;
          /** @description Status */
          status?: string;
          /** @description Started after */
          started_after?: string;
          /** @description Ended before */
          ended_before?: string;
          /** @description Order */
          order?: string;
          /** @description Limit */
          limit?: number;
        };
        header: {
          /** @description Authorization token */
          Authorization: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['handler.ListOtaResponse'];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            'application/json': components['schemas']['handler.ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          content: never;
        };
        /** @description Internal Server Error */
        500: {
          content: never;
        };
      };
    };
    /**
     * Create OTA
     * @description Create a new OTA
     */
    post: {
      parameters: {
        header: {
          /** @description Authorization token */
          Authorization: string;
        };
      };
      /** @description OTA body */
      requestBody?: {
        content: {
          'application/json': components['schemas']['handler.PostOtaBody'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['handler.PostOtaResponse'];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            'application/json': components['schemas']['handler.ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          content: never;
        };
        /** @description Forbidden */
        403: {
          content: never;
        };
        /** @description Conflict */
        409: {
          content: {
            'application/json': components['schemas']['handler.ErrorResponse'];
          };
        };
        /** @description Internal Server Error */
        500: {
          content: never;
        };
      };
    };
  };
  [path: `/v1/ota/${string}`]: {
    /**
     * Get OTA
     * @description Get an OTA
     */
    get: {
      parameters: {
        header: {
          /** @description Authorization token */
          Authorization: string;
        };
        path: {
          /** @description OTA ID */
          ota_id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            'application/json': components['schemas']['handler.GetOtaResponse'];
          };
        };
        /** @description Bad Request */
        400: {
          content: {
            'application/json': components['schemas']['handler.ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          content: never;
        };
        /** @description Not Found */
        404: {
          content: never;
        };
        /** @description Internal Server Error */
        500: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    'handler.ErrorResponse': {
      err?: string;
    };
    'handler.GetOtaResponse': {
      ota?: components['schemas']['model.Ota'];
      states?: components['schemas']['handler.OtaState'][];
    };
    'handler.ListOtaResponse': {
      ota?: components['schemas']['model.Ota'][];
    };
    'handler.OtaState': {
      ota_id?: string;
      state?: string;
      state_data?: string;
      timestamp?: string;
    };
    'handler.PostOtaBody': {
      /** @example ota/test/test-test_feb08a-aed202794d7a1fb253734349377d0914ba2bac083ebf5159798e82e0a9e9ff12-20240108_151551.ota */
      binary_key: string;
      /** @example b855fc74-66f0-4461-8a34-7c4cd778d381 */
      device_id: string;
    };
    'handler.PostOtaResponse': {
      ota?: components['schemas']['model.Ota'];
    };
    'model.Ota': {
      device_id?: string;
      ended_at?: string;
      error_reason?: string;
      id?: string;
      sha256?: string;
      started_at?: string;
      status?: components['schemas']['model.Status'];
      firmware_size?: number;
    };
    /** @enum {string} */
    'model.Status':
      | 'pending'
      | 'in_progress'
      | 'succeeded'
      | 'failed'
      | 'aborted';
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
