/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as BricksRouteImport } from './routes/bricks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyAppsIndexRouteImport } from './routes/my-apps/index'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as ExamplesIndexRouteImport } from './routes/examples/index'
import { Route as MyAppsAppIdRouteImport } from './routes/my-apps/$appId'
import { Route as LearnResourceIdRouteImport } from './routes/learn/$resourceId'
import { Route as ExamplesAppIdRouteImport } from './routes/examples/$appId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const BricksRoute = BricksRouteImport.update({
  id: '/bricks',
  path: '/bricks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAppsIndexRoute = MyAppsIndexRouteImport.update({
  id: '/my-apps/',
  path: '/my-apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesIndexRoute = ExamplesIndexRouteImport.update({
  id: '/examples/',
  path: '/examples/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAppsAppIdRoute = MyAppsAppIdRouteImport.update({
  id: '/my-apps/$appId',
  path: '/my-apps/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnResourceIdRoute = LearnResourceIdRouteImport.update({
  id: '/learn/$resourceId',
  path: '/learn/$resourceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesAppIdRoute = ExamplesAppIdRouteImport.update({
  id: '/examples/$appId',
  path: '/examples/$appId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bricks': typeof BricksRoute
  '/models': typeof ModelsRoute
  '/settings': typeof SettingsRoute
  '/examples/$appId': typeof ExamplesAppIdRoute
  '/learn/$resourceId': typeof LearnResourceIdRoute
  '/my-apps/$appId': typeof MyAppsAppIdRoute
  '/examples': typeof ExamplesIndexRoute
  '/learn': typeof LearnIndexRoute
  '/my-apps': typeof MyAppsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bricks': typeof BricksRoute
  '/models': typeof ModelsRoute
  '/settings': typeof SettingsRoute
  '/examples/$appId': typeof ExamplesAppIdRoute
  '/learn/$resourceId': typeof LearnResourceIdRoute
  '/my-apps/$appId': typeof MyAppsAppIdRoute
  '/examples': typeof ExamplesIndexRoute
  '/learn': typeof LearnIndexRoute
  '/my-apps': typeof MyAppsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bricks': typeof BricksRoute
  '/models': typeof ModelsRoute
  '/settings': typeof SettingsRoute
  '/examples/$appId': typeof ExamplesAppIdRoute
  '/learn/$resourceId': typeof LearnResourceIdRoute
  '/my-apps/$appId': typeof MyAppsAppIdRoute
  '/examples/': typeof ExamplesIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/my-apps/': typeof MyAppsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bricks'
    | '/models'
    | '/settings'
    | '/examples/$appId'
    | '/learn/$resourceId'
    | '/my-apps/$appId'
    | '/examples'
    | '/learn'
    | '/my-apps'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bricks'
    | '/models'
    | '/settings'
    | '/examples/$appId'
    | '/learn/$resourceId'
    | '/my-apps/$appId'
    | '/examples'
    | '/learn'
    | '/my-apps'
  id:
    | '__root__'
    | '/'
    | '/bricks'
    | '/models'
    | '/settings'
    | '/examples/$appId'
    | '/learn/$resourceId'
    | '/my-apps/$appId'
    | '/examples/'
    | '/learn/'
    | '/my-apps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BricksRoute: typeof BricksRoute
  ModelsRoute: typeof ModelsRoute
  SettingsRoute: typeof SettingsRoute
  ExamplesAppIdRoute: typeof ExamplesAppIdRoute
  LearnResourceIdRoute: typeof LearnResourceIdRoute
  MyAppsAppIdRoute: typeof MyAppsAppIdRoute
  ExamplesIndexRoute: typeof ExamplesIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  MyAppsIndexRoute: typeof MyAppsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bricks': {
      id: '/bricks'
      path: '/bricks'
      fullPath: '/bricks'
      preLoaderRoute: typeof BricksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-apps/': {
      id: '/my-apps/'
      path: '/my-apps'
      fullPath: '/my-apps'
      preLoaderRoute: typeof MyAppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/': {
      id: '/examples/'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-apps/$appId': {
      id: '/my-apps/$appId'
      path: '/my-apps/$appId'
      fullPath: '/my-apps/$appId'
      preLoaderRoute: typeof MyAppsAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$resourceId': {
      id: '/learn/$resourceId'
      path: '/learn/$resourceId'
      fullPath: '/learn/$resourceId'
      preLoaderRoute: typeof LearnResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/$appId': {
      id: '/examples/$appId'
      path: '/examples/$appId'
      fullPath: '/examples/$appId'
      preLoaderRoute: typeof ExamplesAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BricksRoute: BricksRoute,
  ModelsRoute: ModelsRoute,
  SettingsRoute: SettingsRoute,
  ExamplesAppIdRoute: ExamplesAppIdRoute,
  LearnResourceIdRoute: LearnResourceIdRoute,
  MyAppsAppIdRoute: MyAppsAppIdRoute,
  ExamplesIndexRoute: ExamplesIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  MyAppsIndexRoute: MyAppsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
